modLoader="javafml"
loaderVersion="[34,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/CAS-ual-TY/INeedThemOres/issues"

[[mods]]
    modId="ineedthemores"
    version="${file.jarVersion}"
    displayName="I Need Them Ores"
    displayURL="https://github.com/CAS-ual-TY/INeedThemOres"
    logoFile="logo.png"
    credits="Mojang and the Minecraft Forge Team."
    authors="CAS_ual_TY"
    description="Generate the Ores now, use them in your Tech Mods when they are updated."
